# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  solutionFolder: './src'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: dotnet restore $(solutionFolder)
  displayName: 'dotnet restore'

- script: dotnet build $(solutionFolder) --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test $(buildConfiguration)'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- script: dotnet pack $(solutionFolder) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet pack $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'

- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'MyGet (lethek)'
    versioningScheme: byEnvVar
    versionEnvVar: version
